name: Build ImmortalWrt for AX3000

on:
  workflow_dispatch:  # 支持手动触发
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile OpenWrt for Redmi AX3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget python3 python3-pip

      - name: Clone ImmortalWrt source (release branch)
        run: |
          git clone -b 23.05 https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt

      - name: Copy custom config and diy script
        run: |
          cp .config immortalwrt/.config
          cp diy-part.sh immortalwrt/diy-part.sh

      - name: Run diy-part.sh
        run: |
          cd immortalwrt
          chmod +x diy-part.sh
          ./diy-part.sh

      - name: Update & install feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Start compiling
        run: |
          cd immortalwrt
          make defconfig
          make -j$(nproc) download V=s || true
          make -j$(nproc) V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: |
            immortalwrt/bin/targets/
